version: '2'
services:
  system:
    container_name: system-cuac-container
    build: .
    ports:
      - "4567:4567"
    volumes:
     - .:/opt/culturaaccesible
     - bundle:/usr/local/bundle

    links:
      - selenium
    command: bash -c "bundle install --jobs 3 && bundle exec rake prepare && bundle exec rake"

  selenium:
    container_name: chrome-cuac-container
    image: selenium/standalone-chrome
    ports:
        - "4444:4444"
    logging:
      driver: none

volumes:
  bundle:
    driver: local
